-- AlterTable
ALTER TABLE "pass" ALTER COLUMN "perk_item_1" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_2" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_3" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_4" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_5" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_6" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_7" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_8" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_9" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_10" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_11" SET DATA TYPE TEXT,
ALTER COLUMN "perk_item_12" SET DATA TYPE TEXT;
